### ISSUE TITLE
SMS Parsing and Adding Transactions automatically by patterns

### ISSUE THREAD

**Issue by yetanothercoder** [dsolonenko/financisto#12]
Support for parsing SMS by patterns:
`<:A:>` - account
`<:P:>` - price
`<::>` - all symbols/words
`<:B:>` - balance (planned for future)
`<:D:>` - date/time (planned for future)

SMS Templates are bound to Category and Account (optional).

Ex. SMS: 
`Pokupka. Karta *5631. Summa 250.00 RUB. NOVYY PROEKT, MOSCOW. 02.10.2017 14:19. Dostupno 34202.82 RUB. Tinkoff.ru`
Template for it: 
`Pokupka. Karta *<:A:>. Summa <:P:> RUB. NOVYY PROEKT<::>`
(if you have account of card type with number ending with `5631` - then this account will be used in transaction, otherwise - the account which is set in Template properties)
or:
`<::>. Summa <:P:> RUB. NOVYY PROEKT<::>` - but in this case the account will not be recognised automatically.

+Added activities/screens for editing/adding SMS templates (from Entity list or Category edit screen), status bar notifications etc., here are screenshots and the built apk: https://www.dropbox.com/sh/s6glynraohv5jbr/AABlxeyfqaKj_Dp2PueFxW1Ba?dl=0

**Comment by yetanothercoder** [comment]
successfully finished and released in play

**Comment by sergey-vorozhtsov** [comment]
ребята, я заметил эту фичу, но не могу понять, как вызвать то этот парсер? смс пришла, а транзакция не появляется. есть где то кнопка типа "просканировать смски"?

**Comment by yetanothercoder** [comment]
@sergey-vorozhtsov нет, само должно после прихода смс, права на чтение смс надо дать, приложение запрашивает их, вот эту тему можно почитать начиная с того сообщения касательно подобных проблема http://4pda.ru/forum/index.php?s=&showtopic=141782&view=findpost&p=68402384
