### ISSUE TITLE
V.1.8.2 last update 11.23.2019. 

### ISSUE THREAD

**Issue by praded2007** [dsolonenko/financisto#120]
The previous version of displaying this menu in the recipient / category column was more convenient
Option for payee/project/location selector not work!

**Comment by praded2007** [comment]
I will wait for changes, but for the better

**Comment by kipdt** [comment]
I loved the filter option which is now gone with the latest update. Hope this comes back. I have tried reverting to an older release through apk but my phone keeps saying app not installed.
