### ISSUE TITLE
Search by payee and category. Last update v. 1.8.2

### ISSUE THREAD

**Issue by praded2007** [dsolonenko/financisto#125]
Revert to previous version of Search by payee and category. This release is not convenient.
The user must choose a search method. The auto search version + alphabetical listing was wonderful.

**Comment by yetanothercoder** [comment]
yes, blotter filters lost all auto-complete-search fields for Category/Project/Payer/Location, @dsolonenko do you plan to restore them or adding some option in settings for activating them back who needs?

**Comment by larogi** [comment]
> filters lost all auto-complete-search fields for Category/Project/Payer/Location  > 
In my case of using the application, such a filter is very necessary. If would was able returned to version of where this implemented, but there is no opportunities.

**Comment by cAc77** [comment]
Please return the filter to the "journal" tab, I beg you. Sorry for my English.

**Comment by yetanothercoder** [comment]
thanks, it was returned in the last beta update.

**Comment by praded2007** [comment]
Wao. But where is one?

**Comment by praded2007** [comment]
Yes.  Found version 1.8.3.  this problem was fixed
