### ISSUE TITLE
SMS price parsing number formating

### ISSUE THREAD

**Issue by thebro** [dsolonenko/financisto#31]
Greetings from Serbia!

Glad to see Financisto finally got SMS handling.
(I've been dreaming of implementing this for years, but never got into Android programming...)

We need more configuration regarding price parsing in order to support different number formatting (e.g. thousand separator and decimal point).

Here is one SMS example from my bank:

> Potrosnja po kartici: 544358******0763 Iznos: 1.349,92 RSD Datum: 01.02.2018. Trgovac: 214 - TEMPO 011 Raspolozivo 24.008,61 RSD br.odobr: 930641

As is currently implemented I cannot parse the text **1.349,92** into number **1349.92**.

**Comment by yetanothercoder** [comment]
Hi, yes, thanks, it'll be fixed in https://github.com/dsolonenko/financisto/issues/22
so you can subscribe to #22 - when we close it - the fix will be released.
