### ISSUE TITLE
Add Transaction: Payee textbox triggers Autofill dropdown

### ISSUE THREAD

**Issue by ryester19** [dsolonenko/financisto#36]
With Android 8.0 and the new Autofill service enabled, selecting the Payee textbox in the Add Transaction screen triggers the Autofill dropdown box. After saving the transaction, I get the "Save password to ***" popup at the bottom of the screen.

I attached some screenshots, just in case if there was any confusion :)

![screenshot_20180207-215418](https://user-images.githubusercontent.com/17807258/35953521-1017bc6e-0c53-11e8-97d9-384731250df9.png)
![screenshot_20180207-215507](https://user-images.githubusercontent.com/17807258/35953524-128db8fe-0c53-11e8-832b-612ae42be2bf.png)

**Comment by dtruebin** [comment]
This one is super annoying and, although I don't know the distribution of Financisto installs per Android version, according to the general [Distribution dashboard](https://developer.android.com/about/dashboards/) on Dev portal, more than 20% of Android devices are now running Oreo and higher.
