### ISSUE TITLE
Payee field cleared after selecting Category ?

### ISSUE THREAD

**Issue by worm6666** [dsolonenko/financisto#38]
On old Android 4.4.2 when I fill the field Payee, and then select Category, all is OK.

On new Android 7.1.1 when I fill Payee field, and then when select Category, the field Payee is cleared. It is really annoying. I cannot find it anywhere in settings...

It is a bug or not ? Or wrong setting that I cannot see ?

Both Financisto are latest 1.8.0.

**Comment by dsolonenko** [comment]
@worm6666 do you have "Don't keep activities" checked in Developer Options by any chance?

**Comment by worm6666** [comment]
SOLVED with Your tip ! Thank You. On old phone it was disabled - on new enabled. Also disabled and tested - works like expected now.
