### ISSUE TITLE
Scrolling issue on Android M

### ISSUE THREAD

**Issue by igor-garin** [dsolonenko/financisto#5]
![2015-12-30 14 46 28](https://cloud.githubusercontent.com/assets/1986287/12052205/8f95cf84-af1d-11e5-9002-1fe6903bc3d3.png)

Text becomes mixed while scrolling on Android M.
I suppose that maybe there is an issue with hardware acceleration.

**Comment by dsolonenko** [comment]
Will have to reproduce it on an actual device.. But you can tick "Force GPU rendering" in the Developer Options as an interim solution. Thanks
