### ISSUE TITLE
SMS not catched on Oreo (android 8.1)

### ISSUE THREAD

**Issue by luckydevil13** [dsolonenko/financisto#54]
battary optimisation off for finacisto, permission applied to read sms.
7.1 was working correctly

**Comment by nekromant** [comment]
@luckydevil13 Just throwing my 2 cents in: SMS are kind of partially working for me on current lineage 15.1 (oreo 8.1). They are worrking for sberbank (900 number) and broken on RosEvroBank. SMS's from bank contain line breaks (?) that weren't correctly handled for some reason.

**Comment by luckydevil13** [comment]
@nekromant
seems sms from number is working? I have priorbank

**Comment by nekromant** [comment]
I guess it's because SMS from sberbank appear to be from number 900 and the other one, 'RosEvroBank' appears to be from either 'RosEvroBank' or 'ROSEVROBANK' (depending on where you pay). The latter one doesn't seem to work.

**Comment by luckydevil13** [comment]
@nekromant , I don't know what exaxtly helps me.. but it works:
batttery optimization off
autostart on
create contact with bank name
recreate sms parcse rules (just resave it - not change)
on/off permissions on sms read
