### ISSUE TITLE
Entered minutes are not saved on Android 6.0.1

### ISSUE THREAD

**Issue by DixonDs** [dsolonenko/financisto#6]
When I add a new transaction and enter the transaction time, minutes are not saved if I use the keyboard to enter it. If I use arrows up and down, then the transaction time is saved correctly.

**Comment by dsolonenko** [comment]
It looks like an issue with the time picker on Android 6 since there are no code changes in this area and it works fine on previous versions..

**Comment by dtruebin** [comment]
@DixonD-git, try switching focus to hours field after entering minutes but before you tap the OK button.
