### ISSUE TITLE
F-Droid distribution

### ISSUE THREAD

**Issue by alensiljak** [dsolonenko/financisto#90]
Similar to #14 and #56, I'd vote for F-Droid distribution. If you need any help, do let me know.

**Comment by klawdhfzasjhaa** [comment]
Second that!

**Comment by dsolonenko** [comment]
Unfortunately, the project uses 2 libraries (achartengine and rfc2445) that are not available anymore in any maven public repo, which makes it not possible to distribute on F-Droid

**Comment by alensiljak** [comment]
Thanks for the feedback!
